### ISSUE TITLE
The results for CIFAR-100 and CUB dataset 

### ISSUE THREAD

**Issue by ZhimaoPeng** [mashijie1028/Happy-CGCD#3]
Thanks for the code, I learned a lot from it ！ However, I encountered the following issues while running the code:

For the CIFAR-100 dataset，I can get the results reported in the paper at stage-0:

![CIFAR-100](https://github.com/user-attachments/assets/82e2ce40-a70b-4854-8cee-43b193e20bd0)

However, the results of stage-1 are quite different from those reported in the paper:

![CIFAR-100-2](https://github.com/user-attachments/assets/987b6329-da8a-426a-9f1b-74354b4612dc)

For the CUB dataset, the results of stage-0 are quite different from those reported in the paper:

![CUB](https://github.com/user-attachments/assets/5337a47c-7ba4-4c81-9ff3-7fe095f44daf)

Looking forward to your reply at your convenience.

**Comment by mashijie1028** [comment]
Hi! Thanks for the question.
A reproducible result in stage-0 is the premise for the later results.
For C100, you could re-run the stage-1 to stage-T continual training. The performance of continual training is relatively unstable compared with stage-0.
For CUB, the issue seems to be the usage of ssb_split. In our released codes, i.e., `get_datasets.py`, in line 195, if `args.num_old_classes > 0`, the ssb_spplits will be overrides. To achieve comparable results, you should use ssb_splits for CUB. Please correct the codes and we will fix them later. Here, I attach the offline ckpt and logs on CUB via [Baidu NetDisk](https://pan.baidu.com/s/1IIOzSIY_7MCCwPJoeyNkfA?pwd=cgcd), which are exactly the same as the reported results. You could also directly begin continual training using this ckpt. Hope this helps!

**Comment by ZhimaoPeng** [comment]
the issue has been solved, thanks!
